### PR TITLE
Handle all exceptions

### LINKED ISSUE #412: Not StandardError exception during error reporting
Hello, I've found a bug that makes Sneakers not to report acknowledge state on error.

Wiki suggests to pass `context_hash` to error notification agents. [link](https://github.com/jondot/sneakers/wiki/Configuration#error-reporter)
```ruby
Sneakers.error_reporters << proc { |exception, _worker, context_hash| Honeybadger.notify(exception, context_hash) }
```
I'm using [Sentry raven](https://github.com/getsentry/raven-ruby) for error notifications. Sometimes it fails to serialize `context_hash` to json because `Bunny::Channel` instance in `delivery_info` of `context_hash` causes
```
SystemStackError: stack level too deep
```

As result:
1. RabbitMQ keeps message as Unacked
2. Such messages number may reach number of prefetched messages for worker
3. Worker hangs without performing any workload

Sneakers handles only `StandardError` and its descendants [here](https://github.com/jondot/sneakers/blob/master/lib/sneakers/error_reporter.rb#L19) and can not handle `SystemStackError` because it is not a `StandardError`.

Previously I [fixed similar bug](https://github.com/jondot/sneakers/pull/373) in another place. And I would be happy to do the same here.

But I think that it would be better to rescue from `Exception` in both places and re-raise exception in case of `Interrupt`, `NoMemoryError` and other exceptions that should not be swallowed.

WDYT?

### PR DESCRIPTION
**Pull request by sharshenov**
Previously Sneakers was able to [handle `StandardError` and `ScriptError`](https://github.com/jondot/sneakers/pull/373) exceptions and their descendants. But there are more exceptions that could cause problems.

* `SystemStackError` (stack level too deep)
* `NoMemoryError`
* custom descendants of `Exception` (e.g. declared by gems)

In case of these exceptions, the handler is unable to report job state to the RabbitMQ. RabbitMQ keeps sending new jobs to the Sneakers until prefetch value reached. It makes Sneakers worker hang without processing any new message.

Closes #412

### CODE REVIEW

**Comment by sharshenov** [comment]
[The failed job of Travis](https://travis-ci.org/github/jondot/sneakers/jobs/698588572) seems to be irrelevant to the PR.

File: lib/sneakers/worker.rb [hunk 1]
```diff
@@ -72,31 +72,31 @@ def process_work(delivery_info, metadata, msg, handler)
           end
           res = block_to_call.call(deserialized_msg, delivery_info, metadata, handler)
         end
-      rescue StandardError, ScriptError => ex
+      rescue SignalException, SystemExit
+        # ServerEngine handles these exceptions, so they are not expected to be raised within the worker.
+        # Nevertheless, they are listed here to ensure that they are not caught by the rescue block below.
+        raise
+      rescue Exception => ex
```
Comment (kalys) [inline lib/sneakers/worker.rb:79]: What about interruption signals? Will they work?

Comment (sharshenov) [reply lib/sneakers/worker.rb:79]: @kalys Look at the [previous `rescue` block](https://github.com/jondot/sneakers/pull/441/files#diff-89d631e42c0689fc74b63e84d8605cdcR75). `Interrupt` is a subclass of `SignalException`.

**Comment by sharshenov** [comment]
@michaelklishin sorry for tagging you, but this PR resolves a bug when errors such as `SystemStackError` may cause Sneakers consumer outage. Any chance of this change to be reviewed?

**Comment by michaelklishin** [comment]
Thank you for spotting this.
